"""Nodes for docs/preregistration_holdout.md."""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd
from scipy import stats

from ...metrics import cluster_bootstrap
from ..reporting.write import _ci, _row

log = logging.getLogger(__name__)


def check_disjoint_all(features: pd.DataFrame, params: dict) -> pd.DataFrame:
    ids = set(features["member_id"])
    for f in params["seen_member_files"]:
        overlap = ids & set(pd.read_parquet(f, columns=["member_id"])["member_id"])
        if overlap:
            raise ValueError(f"{len(overlap)} holdout members also appear in {f}")
    log.info("Holdout cohort: %d members, none in %s", len(ids), params["seen_member_files"])
    return features


def evaluate_level(
    predictions: pd.DataFrame, calibration: pd.DataFrame, params: dict
) -> pd.DataFrame:
    """Member predicted / actual for GLM, LightGBM and recalibrated LightGBM."""
    t = predictions[predictions["split"] == "test"]
    k = dict(zip(calibration["model"], calibration["factor"], strict=True))["gbm"]

    def stat(d: pd.DataFrame) -> dict[str, float]:
        y = d["target_cost"].sum()
        return {
            "glm": (d["pred_glm"] * d["exposure"]).sum() / y,
            "gbm": (d["pred_gbm"] * d["exposure"]).sum() / y,
            "gbm_recalibrated": k * (d["pred_gbm"] * d["exposure"]).sum() / y,
        }

    return cluster_bootstrap(t, "member_id", stat, params["n_boot"], params["seed"])


def write_holdout(
    level: pd.DataFrame,
    cost_ci: pd.DataFrame,
    calibration: pd.DataFrame,
    excess: pd.DataFrame,
    spliced: pd.DataFrame,
    pricing: pd.DataFrame,
    features: pd.DataFrame,
    params: dict,
) -> str:
    k = dict(zip(calibration["model"], calibration["factor"], strict=True))
    L = [
        "# Holdout results (Sample 5)",
        "",
        "Generated by `kedro run --env holdout --pipeline holdout`. Do not edit by hand. "
        "Predictions: `docs/preregistration_holdout.md`. Verdicts: `docs/scorecard.md`.",
        "",
        f"{len(features):,} members (none in Samples 2–4), {features['group_id'].nunique()} "
        "groups, 2008 features → 2009 cost, frozen Sample 2 models. Level factors from Samples "
        f"3–4: LightGBM {k['gbm']:.4f}, GLM {k['glm']:.4f}.",
        "",
        "## H1: member predicted / actual",
        "",
        "| Model | Predicted / actual |",
        "|---|---|",
        f"| GLM | {_row(level, 'glm')} |",
        f"| LightGBM (model of record) | {_row(level, 'gbm')} |",
        f"| LightGBM, recalibrated | {_row(level, 'gbm_recalibrated')} |",
        "",
        f"Gini: GLM {_row(cost_ci, 'glm_gini')}, LightGBM {_row(cost_ci, 'gbm_gini')} "
        "(recalibration doesn't change ranking).",
        "",
        "## Excess loss (logistic claimant model)",
        "",
        "| Attachment | Claimants | Tail | Expected / member | Actual / member | Actual / expected |",
        "|---|---|---|---|---|---|",
    ]
    for name, tab in (("Single GPD", excess), ("Spliced", spliced)):
        for a, d in tab[tab["model"] == "glm"].groupby("attachment"):
            L.append(
                f"| ${a:,} | {d['claimants'].iloc[0]} | {name} | "
                f"{_row(d, 'expected_per_member', '${:,.0f}')} | "
                f"{_row(d, 'actual_per_member', '${:,.0f}')} | "
                f"{_row(d, 'actual_to_expected', '{:.2f}')} |"
            )
    L += [
        "",
        "## Pricing by variant and size band",
        "",
        "| Variant | Size band | Groups | Members | Actual LR | Claims A/E | Specific A/E | "
        "Aggregate breaches (expected) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in pricing.itertuples():
        L.append(
            f"| {r.label} | {r.size_band} | {r.groups} | {r.members:,} | "
            f"{_ci(r.actual_loss_ratio, r.actual_loss_ratio_lo, r.actual_loss_ratio_hi)} | "
            f"{_ci(r.actual_to_expected, r.actual_to_expected_lo, r.actual_to_expected_hi, '{:.2f}')} | "
            f"{_ci(r.specific_a_to_e, r.specific_a_to_e_lo, r.specific_a_to_e_hi, '{:.2f}')} | "
            f"{r.aggregate_hits} ({r.expected_aggregate_hits:.1f}) |"
        )
    L += ["", "Aggregate breaches, central 95% Poisson range of the expected count:"]
    for r in pricing[pricing["size_band"] == "All"].itertuples():
        lo, hi = stats.poisson.ppf([0.025, 0.975], r.expected_aggregate_hits)
        L.append(
            f"- {r.label}: {r.aggregate_hits} observed, "
            f"{r.expected_aggregate_hits:.1f} expected, range {lo:.0f}–{hi:.0f}"
        )
    text = "\n".join(L) + "\n"
    path = Path(params["results_file"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    log.info("Wrote %s", path)
    return text
