"""Follow-up tests in docs/preregistration_followup.md.

F1 scores an independent DE-SynPUF sample (2008 features -> 2009 cost) with the frozen Sample 2
models. F2 tests relative pricing on the Sample 2 2010 test after removing the overall level.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from ...metrics import cluster_bootstrap
from ..reporting.nodes import MODELS
from ..reporting.write import _ci, _row

log = logging.getLogger(__name__)


def check_disjoint(features: pd.DataFrame, frozen_members: pd.DataFrame) -> pd.DataFrame:
    overlap = set(features["member_id"]) & set(frozen_members["member_id"])
    if overlap:
        raise ValueError(f"{len(overlap)} follow-up members also appear in the training sample")
    log.info("Follow-up cohort: %d members, none in the training sample", len(features))
    return features


def _bands(d: pd.DataFrame) -> list[str]:
    return [*sorted(d["size_band"].unique(), key=lambda b: int(b.split("-")[0])), "All"]


def rank_check(priced: pd.DataFrame, params: dict) -> pd.DataFrame:
    """Spearman correlation of expected vs actual group PMPM, intervals resampling groups."""

    def stat(d: pd.DataFrame) -> dict[str, float]:
        return {"spearman": stats.spearmanr(d["expected_pmpm"], d["actual_pmpm"]).statistic}

    return pd.concat(
        [
            cluster_bootstrap(
                priced[priced["model"] == m], "group_id", stat, params["n_boot"], params["seed"]
            ).assign(model=m, groups=int((priced["model"] == m).sum()))
            for m in MODELS
        ],
        ignore_index=True,
    )


def relative_pricing(priced: pd.DataFrame, params: dict) -> pd.DataFrame:
    """Band actual / expected after rescaling expected claims so the overall ratio is 1.

    The factor k = total actual / total expected is recomputed in every resample.
    """
    rows = []
    for m in MODELS:
        pm = priced[priced["model"] == m]
        for b in _bands(pm)[:-1]:

            def stat(d: pd.DataFrame, b=b) -> dict[str, float]:
                k = d["actual_claims"].sum() / d["expected_claims"].sum()
                x = d[d["size_band"] == b]
                if x.empty:
                    return {"relative_a_to_e": np.nan, "k": k}
                return {
                    "relative_a_to_e": x["actual_claims"].sum() / (k * x["expected_claims"].sum()),
                    "k": k,
                }

            ci = cluster_bootstrap(pm, "group_id", stat, params["n_boot"], params["seed"])
            rows.append(ci.assign(model=m, size_band=b, groups=int((pm["size_band"] == b).sum())))
    return pd.concat(rows, ignore_index=True)


def write_followup(
    cost_ci: pd.DataFrame,
    group_ci: pd.DataFrame,
    hcc: pd.DataFrame,
    excess: pd.DataFrame,
    pricing: pd.DataFrame,
    priced: pd.DataFrame,
    ranks: pd.DataFrame,
    s2_ranks: pd.DataFrame,
    s2_relative: pd.DataFrame,
    features: pd.DataFrame,
    params: dict,
) -> str:
    L = [
        "# Follow-up results",
        "",
        "Generated by `kedro run --env followup --pipeline followup`. Do not edit by hand. "
        "Predictions: `docs/preregistration_followup.md`. Verdicts: `docs/scorecard.md`.",
        "",
        f"## F1: Sample 3, 2008 features → 2009 cost ({len(features):,} members, "
        f"{features['group_id'].nunique()} groups, frozen Sample 2 models)",
        "",
        "| Model | MAE ($) | Gini | Predicted / actual |",
        "|---|---|---|---|",
    ]
    for m, label in MODELS.items():
        L.append(
            f"| {label} | {_row(cost_ci, f'{m}_mae', '{:,.0f}')} | {_row(cost_ci, f'{m}_gini')} | "
            f"{_row(cost_ci, f'{m}_predicted_to_actual')} |"
        )
    L += [
        f"| LightGBM − GLM | {_row(cost_ci, 'gbm_minus_glm_mae', '{:,.0f}')} | "
        f"{_row(cost_ci, 'gbm_minus_glm_gini')} | |",
        "",
        "| Attachment | Claimants | Model | AUC | PR-AUC | Top-decile lift |",
        "|---|---|---|---|---|---|",
    ]
    for (a, m), d in hcc[hcc["model"].isin(list(MODELS))].groupby(["attachment", "model"]):
        L.append(
            f"| ${a:,} | {d['positives'].iloc[0]} | {MODELS[m]} | {_row(d, 'auc')} | "
            f"{_row(d, 'pr_auc')} | {_row(d, 'top_decile_lift', '{:.1f}')} |"
        )
    L += [
        "",
        "| Attachment | HCC model | Expected excess / member | Actual excess / member | "
        "Actual / expected |",
        "|---|---|---|---|---|",
    ]
    for (a, m), d in excess.groupby(["attachment", "model"]):
        L.append(
            f"| ${a:,} | {MODELS[m]} | {_row(d, 'expected_per_member', '${:,.0f}')} | "
            f"{_row(d, 'actual_per_member', '${:,.0f}')} | "
            f"{_row(d, 'actual_to_expected', '{:.2f}')} |"
        )
    L += [
        "",
        "| Models | Size band | Groups | Members | Priced LR | Actual LR | Claims A/E | "
        "Specific A/E | Aggregate breaches (expected) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in pricing.itertuples():
        L.append(
            f"| {MODELS[r.model]} | {r.size_band} | {r.groups} | {r.members:,} | "
            f"{r.priced_loss_ratio:.3f} | "
            f"{_ci(r.actual_loss_ratio, r.actual_loss_ratio_lo, r.actual_loss_ratio_hi)} | "
            f"{_ci(r.actual_to_expected, r.actual_to_expected_lo, r.actual_to_expected_hi, '{:.2f}')} | "
            f"{_ci(r.specific_a_to_e, r.specific_a_to_e_lo, r.specific_a_to_e_hi, '{:.2f}')} | "
            f"{r.aggregate_hits} ({r.expected_aggregate_hits:.1f}) |"
        )
    L += ["", "Aggregate breaches, central 95% Poisson range of the expected count:"]
    for r in pricing[pricing["size_band"] == "All"].itertuples():
        lo, hi = stats.poisson.ppf([0.025, 0.975], r.expected_aggregate_hits)
        L.append(
            f"- {MODELS[r.model]}: {r.aggregate_hits} observed, "
            f"{r.expected_aggregate_hits:.1f} expected, range {lo:.0f}–{hi:.0f}"
        )
    L += [
        "",
        "| Models | Groups | Spearman, expected vs actual group PMPM |",
        "|---|---|---|",
        *[
            f"| {MODELS[m]} | {d['groups'].iloc[0]} | {_row(d, 'spearman')} |"
            for m, d in ranks.groupby("model")
        ],
        "",
        "## F2: Sample 2 test (2009 → 2010), relative pricing",
        "",
        "| Models | Size band | Groups | Rescaled claims A/E | k (actual / expected, all groups) |",
        "|---|---|---|---|---|",
    ]
    for (m, b), d in s2_relative.groupby(["model", "size_band"], sort=False):
        L.append(
            f"| {MODELS[m]} | {b} | {d['groups'].iloc[0]} | "
            f"{_row(d, 'relative_a_to_e', '{:.2f}')} | {_row(d, 'k', '{:.3f}')} |"
        )
    L += [
        "",
        "| Models | Groups | Spearman, expected vs actual group PMPM |",
        "|---|---|---|",
        *[
            f"| {MODELS[m]} | {d['groups'].iloc[0]} | {_row(d, 'spearman')} |"
            for m, d in s2_ranks.groupby("model")
        ],
        "",
    ]
    text = "\n".join(L)
    path = Path(params["results_file"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    log.info("Wrote %s", path)
    return text
