"""Nodes for docs/preregistration_aggregate.md."""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd
from scipy import stats

from ...metrics import cluster_bootstrap
from ..reporting.write import _row

log = logging.getLogger(__name__)


def evaluate_simulation(priced: pd.DataFrame, params: dict) -> pd.DataFrame:
    """PIT variance, mean squared z and breach counts per simulation arm, resampling groups."""

    def stat(d: pd.DataFrame) -> dict[str, float]:
        z = (d["actual_net"] - d["expected_net"]) / d["net_sim_sd"]
        return {
            "pit_var": float(d["pit"].var()),
            "z2": float((z**2).mean()),
            "exp_agg_pmpm": float(d["expected_aggregate"].sum() / d["member_months"].sum()),
        }

    rows = []
    for m, d in priced.groupby("model", sort=False):
        ci = cluster_bootstrap(d, "group_id", stat, params["n_boot"], params["seed"])
        expected = float(d["p_aggregate_hit"].sum())
        lo, hi = stats.poisson.ppf([0.025, 0.975], expected)
        rows.append(
            ci.assign(
                model=m,
                label=d["label"].iloc[0],
                groups=len(d),
                breaches=int((d["actual_aggregate"] > 0).sum()),
                expected_breaches=expected,
                poisson_lo=lo,
                poisson_hi=hi,
            )
        )
    return pd.concat(rows, ignore_index=True)


def write_aggtest(
    evaluation: pd.DataFrame, pricing: pd.DataFrame, features: pd.DataFrame, params: dict
) -> str:
    L = [
        "# Aggregate-layer simulation test (Sample 6)",
        "",
        "Generated by `kedro run --env aggtest --pipeline aggtest`. Do not edit by hand. "
        "Predictions: `docs/preregistration_aggregate.md`. Verdicts: `docs/scorecard.md`.",
        "",
        f"{len(features):,} members (none in Samples 2–5), {features['group_id'].nunique()} groups, "
        "2008 features → 2009 cost. Both arms: recalibrated LightGBM cost, logistic claimants, "
        "spliced tail. Intervals resample groups. A uniform PIT has variance 1/12 = 0.0833.",
        "",
        "| Simulation | PIT variance | Mean squared z | Aggregate breaches (expected; 95% Poisson range) "
        "| Expected aggregate cost PMPM |",
        "|---|---|---|---|---|",
    ]
    for _m, d in evaluation.groupby("model", sort=False):
        r = d.iloc[0]
        L.append(
            f"| {r['label']} | {_row(d, 'pit_var', '{:.4f}')} | {_row(d, 'z2', '{:.2f}')} | "
            f"{r['breaches']} ({r['expected_breaches']:.1f}; {r['poisson_lo']:.0f}–"
            f"{r['poisson_hi']:.0f}) | {_row(d, 'exp_agg_pmpm', '${:.3f}')} |"
        )
    L += ["", "Group claims A/E (same in both arms; only the simulation differs):", ""]
    allrows = pricing[pricing["size_band"] == "All"]
    for r in allrows.itertuples():
        L.append(
            f"- {r.label}: {r.actual_to_expected:.3f} "
            f"[{r.actual_to_expected_lo:.3f}–{r.actual_to_expected_hi:.3f}]"
        )
    text = "\n".join(L) + "\n"
    path = Path(params["results_file"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    log.info("Wrote %s", path)
    return text
