-- One-time Snowflake setup for group-underwriting. Run in a Snowsight worksheet as ACCOUNTADMIN.
-- 1. Generate a key pair on your own machine (never paste the private key anywhere but the
--    environment secret):
--      openssl genrsa 2048 | openssl pkcs8 -topk8 -nocrypt -out gu_rsa_key.p8
--      openssl rsa -in gu_rsa_key.p8 -pubout -out gu_rsa_key.pub
-- 2. Paste the public key body (without the BEGIN/END lines) below, then run this file.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS GU_ROLE;
CREATE WAREHOUSE IF NOT EXISTS GU_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS GROUP_UNDERWRITING;
CREATE SCHEMA IF NOT EXISTS GROUP_UNDERWRITING.RAW;
CREATE SCHEMA IF NOT EXISTS GROUP_UNDERWRITING.KEDRO;
CREATE SCHEMA IF NOT EXISTS GROUP_UNDERWRITING.STG;
CREATE SCHEMA IF NOT EXISTS GROUP_UNDERWRITING.MART;

GRANT USAGE, OPERATE ON WAREHOUSE GU_WH TO ROLE GU_ROLE;
GRANT ALL ON DATABASE GROUP_UNDERWRITING TO ROLE GU_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE GROUP_UNDERWRITING TO ROLE GU_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE GROUP_UNDERWRITING TO ROLE GU_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE GROUP_UNDERWRITING TO ROLE GU_ROLE;

CREATE USER IF NOT EXISTS GU_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = GU_ROLE
  DEFAULT_WAREHOUSE = GU_WH
  RSA_PUBLIC_KEY = '<paste public key body here>';
GRANT ROLE GU_ROLE TO USER GU_SVC;

-- Optional: separate database for the manual "Snowflake" GitHub Actions workflow (synthetic data).
CREATE DATABASE IF NOT EXISTS GROUP_UNDERWRITING_CI;
GRANT ALL ON DATABASE GROUP_UNDERWRITING_CI TO ROLE GU_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE GROUP_UNDERWRITING_CI TO ROLE GU_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE GROUP_UNDERWRITING_CI TO ROLE GU_ROLE;
