"""Under-65 subgroup check (docs/preregistration_under65.md).

Run from the repo root after the followup, retest, holdout and aggtest runs:
    uv run python scripts/under65_check.py
"""

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from group_underwriting.metrics import classification_metrics, cluster_bootstrap, gini
from group_underwriting.pipelines.aggtest.nodes import evaluate_simulation
from group_underwriting.pipelines.features.nodes import assign_groups
from group_underwriting.pipelines.pricing.nodes import price_variants, summarize_by_band
from group_underwriting.pipelines.reporting.nodes import evaluate_excess
from group_underwriting.pipelines.reporting.write import _row
from group_underwriting.pipelines.tail.nodes import expected_excess, spliced_excess

ROOT = "data/real"
SAMPLES = [3, 4, 5, 6]
N_BOOT, SEED = 500, 9
P = yaml.safe_load(
    Path("conf/base/parameters.yml")
    .read_text()
    .replace("${runtime_params:data_root,${globals:data_root}}", ROOT)
)
cost = pickle.load(open(f"{ROOT}/06_models/cost_models.pkl", "rb"))
cal = pd.read_parquet(f"{ROOT}/07_model_output/level_calibration.parquet")
tail = pd.read_parquet(f"{ROOT}/07_model_output/tail_fit.parquet")
upper = pd.read_parquet(f"{ROOT}/07_model_output/upper_tail_fit.parquet")
k = float(cal.set_index("model").at["gbm", "factor"])

feats, preds = [], []
for s in SAMPLES:
    f = pd.read_parquet(f"data/sample{s}/04_feature/features.parquet")
    p = pd.read_parquet(f"data/sample{s}/07_model_output/predictions.parquet")
    feats.append(f.assign(sample=s))
    preds.append(p.assign(sample=s, age=p["member_id"].map(f.set_index("member_id")["age"])))
allf, allp = pd.concat(feats), pd.concat(preds)
f = allf[allf["age"] < 65].copy()
p = allp[allp["member_id"].isin(f["member_id"])].copy()
p["pred_rec"] = p["pred_gbm"] * k

# Member level
t = p.merge(f[["member_id", "target_rate"]], on="member_id", suffixes=("", "_f"))


def member_stat(d):
    y = d["target_cost"].to_numpy()
    out = {
        "pred_to_actual": (d["pred_rec"] * d["exposure"]).sum() / y.sum(),
        "gini": gini(
            d["target_rate"].to_numpy(), d["pred_rec"].to_numpy(), d["exposure"].to_numpy()
        ),
    }
    for a in (25000, 50000):
        out[f"auc_{a}"] = classification_metrics((y > a).astype(int), d[f"p_glm_{a}"].to_numpy())[
            "auc"
        ]
    return out


member = cluster_bootstrap(t, "member_id", member_stat, N_BOOT, SEED)
att = P["attachment_points"]
spl = spliced_excess(p, tail, upper, att)
excess = evaluate_excess(spl, att, {"n_boot": N_BOOT, "seed": SEED})

# Groups re-cut from under-65 members only
cohort = f[["member_id", "state", "county"]].assign(split="test")
g = assign_groups(cohort, P["groups"])
f2 = f.drop(columns=["group_id", "group_size", "size_band"]).merge(
    g[["member_id", "group_id", "group_size", "size_band"]], on="member_id"
)
f2["split"] = "test"
p2 = p.drop(columns=["group_id"]).merge(f2[["member_id", "group_id"]], on="member_id")
p2["split"] = "test"
single = expected_excess(p2, tail, att)
spl2 = spliced_excess(p2, tail, upper, att)

# Ratio pool from 65+ members of Samples 3-5 (the subgroup itself is left out)
pool_src = allp[(allp["sample"] <= 5) & (allp["age"] >= 65) & (allp["split"] == "test")]
rate = pool_src["pred_gbm"] * k
edges = np.quantile(rate, np.linspace(0, 1, 11)[:-1])
edges[0] = -np.inf
band = np.searchsorted(edges, rate, side="right") - 1
pool = pd.DataFrame(
    {
        "band_lo": edges[band],
        "ratio": (pool_src["target_cost"] / (rate * pool_src["exposure"])).to_numpy(),
    }
)
variants = {"record": {**P["pricing_variants"]["record"]}}
pricing = {**P["pricing"], "n_boot": N_BOOT}
priced = price_variants(f2, p2, single, spl2, cost, cal, variants, pricing, pool)
bands = summarize_by_band(priced, pricing)
sim = evaluate_simulation(priced, {"n_boot": N_BOOT, "seed": SEED})

allrow = bands[bands["size_band"] == "All"].iloc[0]
L = [
    "# Under-65 subgroup check (Samples 3–6)",
    "",
    "Generated by `scripts/under65_check.py`. Predictions: `docs/preregistration_under65.md`. "
    "Not a holdout: these members were scored before as part of whole samples.",
    "",
    f"{len(f):,} members under 65 ({len(f) / len(allf):.1%} of Samples 3–6), "
    f"{f2['group_id'].nunique()} groups re-cut from them. Model of record: recalibrated "
    "LightGBM cost, logistic claimants, spliced tail, empirical simulation (ratio pool from 65+ "
    "members of Samples 3–5). Mean allowed cost: under 65 "
    f"${f['target_cost'].mean():,.0f}, 65+ ${allf.loc[allf['age'] >= 65, 'target_cost'].mean():,.0f}.",
    "",
    "| Measure | Result |",
    "|---|---|",
    f"| Member predicted / actual | {_row(member, 'pred_to_actual')} |",
    f"| Member Gini | {_row(member, 'gini')} |",
    f"| Logistic AUC, $25k | {_row(member, 'auc_25000')} |",
    f"| Logistic AUC, $50k | {_row(member, 'auc_50000')} |",
    f"| Group claims A/E | {allrow['actual_to_expected']:.3f} "
    f"[{allrow['actual_to_expected_lo']:.3f}–{allrow['actual_to_expected_hi']:.3f}] |",
    f"| Specific A/E | {allrow['specific_a_to_e']:.2f} "
    f"[{allrow['specific_a_to_e_lo']:.2f}–{allrow['specific_a_to_e_hi']:.2f}] |",
    f"| PIT variance (uniform 0.0833) | {_row(sim, 'pit_var', '{:.4f}')} |",
    f"| Mean squared z (target 1) | {_row(sim, 'z2', '{:.2f}')} |",
]
for a, d in excess[excess["model"] == "glm"].groupby("attachment"):
    L.append(
        f"| Excess A/E above ${a:,} ({d['claimants'].iloc[0]} claimants) | "
        f"{_row(d, 'actual_to_expected', '{:.2f}')} |"
    )
L += ["", "| Size band | Groups | Claims A/E |", "|---|---|---|"]
for r in bands[bands["size_band"] != "All"].itertuples():
    L.append(
        f"| {r.size_band} | {r.groups} | {r.actual_to_expected:.3f} "
        f"[{r.actual_to_expected_lo:.3f}–{r.actual_to_expected_hi:.3f}] |"
    )
out = Path("docs/under65/results.md")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
print("\n".join(L))
