"""Results page for docs/preregistration_retest.md."""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from ..reporting.nodes import MODELS
from ..reporting.write import _ci, _row

log = logging.getLogger(__name__)


def write_retest(
    cost_ci: pd.DataFrame,
    hcc: pd.DataFrame,
    tail_fit: pd.DataFrame,
    upper_fit: pd.DataFrame,
    excess: pd.DataFrame,
    spliced: pd.DataFrame,
    pricing: pd.DataFrame,
    features: pd.DataFrame,
    params: dict,
) -> str:
    f1, f2 = tail_fit.iloc[0], upper_fit.iloc[0]
    L = [
        "# Re-test results",
        "",
        "Generated by `kedro run --env retest --pipeline retest`. Do not edit by hand. "
        "Predictions: `docs/preregistration_retest.md`. Verdicts: `docs/scorecard.md`.",
        "",
        f"Sample 4, 2008 features → 2009 cost: {len(features):,} members (none in Samples 2 or "
        f"3), {features['group_id'].nunique()} groups, frozen Sample 2 models.",
        "",
        "## R1: LightGBM vs GLM",
        "",
        "| Model | MAE ($) | Gini | Predicted / actual |",
        "|---|---|---|---|",
        *[
            f"| {label} | {_row(cost_ci, f'{m}_mae', '{:,.0f}')} | {_row(cost_ci, f'{m}_gini')} | "
            f"{_row(cost_ci, f'{m}_predicted_to_actual')} |"
            for m, label in MODELS.items()
        ],
        f"| LightGBM − GLM | {_row(cost_ci, 'gbm_minus_glm_mae', '{:,.0f}')} | "
        f"{_row(cost_ci, 'gbm_minus_glm_gini')} | |",
        "",
        "| Attachment | Claimants | Logistic AUC | LightGBM AUC | LightGBM − logistic |",
        "|---|---|---|---|---|",
    ]
    for a, d in hcc.groupby("attachment"):
        L.append(
            f"| ${a:,} | {d['positives'].iloc[0]} | {_row(d[d['model'] == 'glm'], 'auc')} | "
            f"{_row(d[d['model'] == 'gbm'], 'auc')} | "
            f"{_row(d[d['model'] == 'gbm_minus_glm'], 'auc')} |"
        )
    L += [
        "",
        "## R2: spliced tail",
        "",
        f"Frozen GPD above ${f1['threshold']:,.0f}: ξ = {f1['xi']:.3f}, σ = ${f1['sigma']:,.0f}. "
        f"Upper GPD above ${f2['threshold']:,.0f} (Sample 2 training + Sample 3, "
        f"{int(f2['n_exceed'])} exceedances): ξ₂ = {f2['xi']:.3f}, σ₂ = ${f2['sigma']:,.0f}, "
        f"KS p = {f2['ks_pvalue']:.3g}.",
        "",
        "| Attachment | Claimants | Tail | Expected excess / member | Actual excess / member | "
        "Actual / expected |",
        "|---|---|---|---|---|---|",
    ]
    for name, tab in (("Single GPD", excess), ("Spliced", spliced)):
        for a, d in tab[tab["model"] == "glm"].groupby("attachment"):
            L.append(
                f"| ${a:,} | {d['claimants'].iloc[0]} | {name} | "
                f"{_row(d, 'expected_per_member', '${:,.0f}')} | "
                f"{_row(d, 'actual_per_member', '${:,.0f}')} | "
                f"{_row(d, 'actual_to_expected', '{:.2f}')} |"
            )
    L += [
        "",
        "Claimant probabilities from the logistic model (model of record).",
        "",
        "## R3: pricing replication (single GPD)",
        "",
        "| Models | Size band | Groups | Members | Actual LR | Claims A/E | Specific A/E | "
        "Aggregate breaches (expected) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in pricing.itertuples():
        L.append(
            f"| {MODELS[r.model]} | {r.size_band} | {r.groups} | {r.members:,} | "
            f"{_ci(r.actual_loss_ratio, r.actual_loss_ratio_lo, r.actual_loss_ratio_hi)} | "
            f"{_ci(r.actual_to_expected, r.actual_to_expected_lo, r.actual_to_expected_hi, '{:.2f}')} | "
            f"{_ci(r.specific_a_to_e, r.specific_a_to_e_lo, r.specific_a_to_e_hi, '{:.2f}')} | "
            f"{r.aggregate_hits} ({r.expected_aggregate_hits:.1f}) |"
        )
    text = "\n".join(L) + "\n"
    path = Path(params["results_file"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    log.info("Wrote %s", path)
    return text
